[build]
  command = "npm run build"
  publish = "netlify-dist"

[build.environment]
  NODE_VERSION = "22.13.0"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

